[package]
name = "compact_bigint"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "quickcheck",
  "arbitrary",
  "serde",
  "rand",
]
debug_structure = [
]
quickcheck = [
  "dep:quickcheck",
  "num-bigint/quickcheck",
]
arbitrary = [
  "dep:arbitrary",
  "num-bigint/arbitrary",
]
serde = [
  "dep:serde",
  "num-bigint/serde",
]
rand = [
  "dep:rand",
  "num-bigint/rand",
]

[dependencies]
num-bigint = "^0.4.6"
duplicate = "^2.0.1"
paste = "^1.0.5"
quickcheck_macros = "1.2.0"

[dependencies.num-integer]
version = "^0.1.46"
default-features = false
features = [
  "i128",
]

[dependencies.num-traits]
version = "^0.2.18"
default-features = false
features = [
  "i128",
]

[dependencies.rand]
optional = true
version = "0.8"
default-features = false

[dependencies.serde]
optional = true
version = "1.0"
default-features = false

[dependencies.quickcheck]
optional = true
version = "1"

[dependencies.arbitrary]
optional = true
version = "1"
default-features = false

[dependencies.test_suite_macro]
version = "0.1.0"

[dev-dependencies]
num-bigint = { version = "^0.4.0", features = [
  "rand",
] }
rand = { version = "^0.8.4" }
criterion = { version = "^0.8.2", features = [
  "html_reports",
] }

[[bench]]
name = "benchmark"
harness = false
