[package]
name = "compact_bigint"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
]
unsafe_encoding = [
]
i128_digit = [
]
debug_structure = [
]

[dependencies]
num-bigint = { version = "^0.4.0" }
num-traits = "^0.2.12"
num-integer = "^0.1.43"
match_ident = { path = "../match_ident" }
duplicate = "^2.0.1"
paste = "^1.0.5"

[dev-dependencies]
num-bigint = { version = "^0.4.0", features = [
  "rand",
] }
rand = { version = "^0.8.4" }
criterion = { version = "^0.8.2", features = [
  "html_reports",
] }
num = "^0.4.0"

[[bench]]
name = "benchmark"
harness = false
